/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.formulariosbebidas;

/**
 *
 * @author javam2019
 */
public class jIntBebidasFC extends javax.swing.JInternalFrame {

    /**
     * Creates new form jIntComboIndividualHamburguesas
     */
    public jIntBebidasFC() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnBC = new javax.swing.JButton();
        jBtnBF = new javax.swing.JButton();
        jLblBF = new javax.swing.JLabel();
        jLblBC = new javax.swing.JLabel();

        jBtnBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBCActionPerformed(evt);
            }
        });

        jBtnBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBFActionPerformed(evt);
            }
        });

        jLblBF.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLblBF.setText("Bebidas Frias");

        jLblBC.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLblBC.setText("Bebidas Calientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnBF, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnBC, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblBC)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLblBF)))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jBtnBF, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblBF)
                .addGap(67, 67, 67)
                .addComponent(jBtnBC, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblBC)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBCActionPerformed

    }//GEN-LAST:event_jBtnBCActionPerformed

    private void jBtnBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnBC;
    public javax.swing.JButton jBtnBF;
    private javax.swing.JLabel jLblBC;
    private javax.swing.JLabel jLblBF;
    // End of variables declaration//GEN-END:variables
}
