/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author javam2019
 */
public class jIntCIH3 extends javax.swing.JInternalFrame {

    /**
     * Creates new form jIntComboIndividualHamburguesas
     */
    public jIntCIH3() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnIH3 = new javax.swing.JButton();
        jBtnCH3 = new javax.swing.JButton();
        jLblCH3 = new javax.swing.JLabel();
        jLblPrecioC3 = new javax.swing.JLabel();
        jLblIH3 = new javax.swing.JLabel();
        jLblPrecioI3 = new javax.swing.JLabel();

        jBtnIH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIH3ActionPerformed(evt);
            }
        });

        jBtnCH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCH3ActionPerformed(evt);
            }
        });

        jLblCH3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLblCH3.setText("Combo");

        jLblPrecioC3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLblPrecioC3.setText("Q50.00");

        jLblIH3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLblIH3.setText("Individual");

        jLblPrecioI3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLblPrecioI3.setText("Q20.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnCH3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnIH3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCH3)
                            .addComponent(jLblPrecioC3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLblPrecioI3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jLblIH3)))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jBtnCH3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblCH3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblPrecioC3)
                .addGap(46, 46, 46)
                .addComponent(jBtnIH3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblIH3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblPrecioI3)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIH3ActionPerformed

    }//GEN-LAST:event_jBtnIH3ActionPerformed

    private void jBtnCH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCH3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCH3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnCH3;
    public javax.swing.JButton jBtnIH3;
    private javax.swing.JLabel jLblCH3;
    private javax.swing.JLabel jLblIH3;
    private javax.swing.JLabel jLblPrecioC3;
    private javax.swing.JLabel jLblPrecioI3;
    // End of variables declaration//GEN-END:variables
}
