/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author javam2019
 */
public class JintDescripcionCombo extends javax.swing.JInternalFrame {

    /**
     * Creates new form JintOrdernarH1
     */
    public JintDescripcionCombo() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNombreCombo = new javax.swing.JLabel();
        jLblImgCombo = new javax.swing.JLabel();
        jLblDescpCombo = new javax.swing.JLabel();
        jLblPrecio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCmbTamanioCombo = new javax.swing.JComboBox<>();
        jLblSnackCombo = new javax.swing.JLabel();
        jCmbBebida = new javax.swing.JComboBox<>();
        JBtnRegresar = new javax.swing.JButton();
        jBtnAñadir = new javax.swing.JButton();
        jLblSnackId = new javax.swing.JLabel();
        jLblBebidaID = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        jLblProductPrincipal = new javax.swing.JLabel();
        jTxtCantidad = new javax.swing.JTextField();
        jBtnMas = new javax.swing.JButton();
        jBtnMenos = new javax.swing.JButton();
        jLblPrecioPrincipal = new javax.swing.JLabel();
        jLblSnackPrecio = new javax.swing.JLabel();
        jLblProductPrincipal3 = new javax.swing.JLabel();
        jLblPrecioBebida = new javax.swing.JLabel();
        jLblProductPrincipal4 = new javax.swing.JLabel();
        jLblProductPrincipal5 = new javax.swing.JLabel();
        jLblPrincipalID = new javax.swing.JLabel();
        jLblAdvertencia2 = new javax.swing.JLabel();
        jLblAdvertencia1 = new javax.swing.JLabel();
        jLblAdvertencia = new javax.swing.JLabel();
        jLblAdvertencia3 = new javax.swing.JLabel();

        jLblNombreCombo.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLblNombreCombo.setText("Nombre Combo");

        jLblDescpCombo.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 16)); // NOI18N
        jLblDescpCombo.setForeground(new java.awt.Color(102, 0, 255));
        jLblDescpCombo.setText("Descripción");

        jLblPrecio.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLblPrecio.setText("Q.123456");

        jLabel5.setFont(new java.awt.Font("Elephant", 1, 30)); // NOI18N
        jLabel5.setText("Tamaño:");

        jCmbTamanioCombo.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jCmbTamanioCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLblSnackCombo.setFont(new java.awt.Font("HP Simplified", 1, 25)); // NOI18N
        jLblSnackCombo.setForeground(new java.awt.Color(255, 204, 0));
        jLblSnackCombo.setText("Papas");

        jCmbBebida.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jCmbBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JBtnRegresar.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        JBtnRegresar.setText("Regresar");

        jBtnAñadir.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jBtnAñadir.setText("Añadir a la orden");

        jLblSnackId.setText("IDSnack");

        jLblBebidaID.setText("IDBebida");

        Cantidad.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        Cantidad.setText("Cantidad:");

        jLblProductPrincipal.setFont(new java.awt.Font("HP Simplified", 1, 25)); // NOI18N
        jLblProductPrincipal.setForeground(new java.awt.Color(255, 204, 0));
        jLblProductPrincipal.setText("Hamburguesa");

        jTxtCantidad.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jTxtCantidad.setText("1");

        jBtnMas.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jBtnMas.setText("+");

        jBtnMenos.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jBtnMenos.setText("-");

        jLblPrecioPrincipal.setFont(new java.awt.Font("Dialog", 3, 22)); // NOI18N
        jLblPrecioPrincipal.setText("Precio");

        jLblSnackPrecio.setFont(new java.awt.Font("Dialog", 3, 22)); // NOI18N
        jLblSnackPrecio.setText("Precio");

        jLblProductPrincipal3.setFont(new java.awt.Font("Elephant", 1, 30)); // NOI18N
        jLblProductPrincipal3.setText("Acompañamiento:");

        jLblPrecioBebida.setFont(new java.awt.Font("Dialog", 3, 22)); // NOI18N
        jLblPrecioBebida.setText("Precio");

        jLblProductPrincipal4.setFont(new java.awt.Font("Elephant", 1, 30)); // NOI18N
        jLblProductPrincipal4.setText("Bebida: ");

        jLblProductPrincipal5.setFont(new java.awt.Font("Elephant", 1, 30)); // NOI18N
        jLblProductPrincipal5.setText("Hamburguesa: ");

        jLblPrincipalID.setText("IDPrincipal");

        jLblAdvertencia2.setFont(new java.awt.Font("Gill Sans MT", 1, 35)); // NOI18N
        jLblAdvertencia2.setForeground(new java.awt.Color(51, 255, 51));
        jLblAdvertencia2.setText("*");

        jLblAdvertencia1.setFont(new java.awt.Font("Gill Sans MT", 1, 35)); // NOI18N
        jLblAdvertencia1.setForeground(new java.awt.Color(51, 255, 51));
        jLblAdvertencia1.setText("*");

        jLblAdvertencia.setFont(new java.awt.Font("Gill Sans MT", 1, 35)); // NOI18N
        jLblAdvertencia.setForeground(new java.awt.Color(51, 255, 51));
        jLblAdvertencia.setText("*");

        jLblAdvertencia3.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        jLblAdvertencia3.setForeground(new java.awt.Color(51, 255, 51));
        jLblAdvertencia3.setLabelFor(jLblPrecio);
        jLblAdvertencia3.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(JBtnRegresar)
                        .addGap(77, 77, 77)
                        .addComponent(jBtnAñadir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblSnackCombo)
                                    .addComponent(jLblSnackId))
                                .addGap(60, 60, 60)
                                .addComponent(jLblSnackPrecio)
                                .addGap(22, 22, 22)
                                .addComponent(jLblAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLblProductPrincipal3))
                        .addGap(421, 421, 421)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblProductPrincipal4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCmbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLblBebidaID, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addComponent(jLblPrecioBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLblAdvertencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLblImgCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblPrecio)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLblAdvertencia3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblNombreCombo)
                                            .addComponent(jLblDescpCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(437, 437, 437)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cantidad)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnMenos)
                                        .addGap(0, 0, 0)
                                        .addComponent(jTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jBtnMas))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(322, 322, 322)
                                        .addComponent(jLblProductPrincipal5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCmbTamanioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(266, 266, 266)
                                        .addComponent(jLblPrincipalID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLblProductPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLblPrecioPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(3, 3, 3)
                                .addComponent(jLblAdvertencia1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblNombreCombo)
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLblPrecio))
                                    .addComponent(jLblAdvertencia3))
                                .addGap(13, 13, 13)
                                .addComponent(jLblDescpCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLblProductPrincipal5))
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCmbTamanioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLblPrincipalID)
                                                    .addComponent(jLblProductPrincipal)
                                                    .addComponent(jLblPrecioPrincipal)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLblAdvertencia1))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Cantidad)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnMenos)
                                    .addComponent(jTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtnMas)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLblImgCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblProductPrincipal4)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCmbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLblBebidaID))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLblPrecioBebida))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLblAdvertencia2))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLblProductPrincipal3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLblSnackCombo)
                                .addGap(4, 4, 4)
                                .addComponent(jLblSnackId))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLblSnackPrecio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLblAdvertencia)))))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtnRegresar)
                    .addComponent(jBtnAñadir))
                .addGap(50, 50, 50))
        );

        jLblDescpCombo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Cantidad;
    public javax.swing.JButton JBtnRegresar;
    public javax.swing.JButton jBtnAñadir;
    public javax.swing.JButton jBtnMas;
    public javax.swing.JButton jBtnMenos;
    public javax.swing.JComboBox<String> jCmbBebida;
    public javax.swing.JComboBox<String> jCmbTamanioCombo;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLblAdvertencia;
    public javax.swing.JLabel jLblAdvertencia1;
    public javax.swing.JLabel jLblAdvertencia2;
    public javax.swing.JLabel jLblAdvertencia3;
    public javax.swing.JLabel jLblBebidaID;
    public javax.swing.JLabel jLblDescpCombo;
    public javax.swing.JLabel jLblImgCombo;
    public javax.swing.JLabel jLblNombreCombo;
    public javax.swing.JLabel jLblPrecio;
    public javax.swing.JLabel jLblPrecioBebida;
    public javax.swing.JLabel jLblPrecioPrincipal;
    public javax.swing.JLabel jLblPrincipalID;
    public javax.swing.JLabel jLblProductPrincipal;
    private javax.swing.JLabel jLblProductPrincipal3;
    private javax.swing.JLabel jLblProductPrincipal4;
    public javax.swing.JLabel jLblProductPrincipal5;
    public javax.swing.JLabel jLblSnackCombo;
    public javax.swing.JLabel jLblSnackId;
    public javax.swing.JLabel jLblSnackPrecio;
    public javax.swing.JTextField jTxtCantidad;
    // End of variables declaration//GEN-END:variables
}
