/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author javam2019
 */
public class JintDescripcionProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form JintDescripcionProducto
     */
    public JintDescripcionProducto() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblImgProducto = new javax.swing.JLabel();
        jLblNombreProducto = new javax.swing.JLabel();
        jLblPrecioCombo = new javax.swing.JLabel();
        jLblDescpProducto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCmbTamanioProducto = new javax.swing.JComboBox<>();
        JBtnRegresarProduc = new javax.swing.JButton();
        jBtnAñadirProduc = new javax.swing.JButton();
        jLblWarningProducto = new javax.swing.JLabel();
        JlblAdvertencia = new javax.swing.JLabel();
        jBtnMas = new javax.swing.JButton();
        jBtnMenos = new javax.swing.JButton();
        jTxtCantidad = new javax.swing.JTextField();
        Cantidad = new javax.swing.JLabel();
        jLblPtId = new javax.swing.JLabel();
        jLblPrecioCombo1 = new javax.swing.JLabel();
        jLblTamanio = new javax.swing.JLabel();

        jLblNombreProducto.setFont(new java.awt.Font("Dialog", 3, 38)); // NOI18N
        jLblNombreProducto.setText("Nombre Producto");

        jLblPrecioCombo.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLblPrecioCombo.setText("Precio");

        jLblDescpProducto.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jLblDescpProducto.setText("Descripción");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jLabel5.setText("Tamaño:");

        jCmbTamanioProducto.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        jCmbTamanioProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JBtnRegresarProduc.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        JBtnRegresarProduc.setText("Regresar");

        jBtnAñadirProduc.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jBtnAñadirProduc.setText("Añadir a la orden");

        jLblWarningProducto.setFont(new java.awt.Font("Dialog", 2, 20)); // NOI18N
        jLblWarningProducto.setForeground(new java.awt.Color(255, 0, 0));
        jLblWarningProducto.setText("!El producto solo cuenta con un tamaño¡");

        JlblAdvertencia.setFont(new java.awt.Font("Dialog", 1, 35)); // NOI18N
        JlblAdvertencia.setForeground(new java.awt.Color(0, 153, 0));
        JlblAdvertencia.setText("*");

        jBtnMas.setFont(new java.awt.Font("Dialog", 1, 35)); // NOI18N
        jBtnMas.setText("+");

        jBtnMenos.setFont(new java.awt.Font("Dialog", 1, 35)); // NOI18N
        jBtnMenos.setText("-");

        jTxtCantidad.setFont(new java.awt.Font("Dialog", 0, 35)); // NOI18N
        jTxtCantidad.setText("1");

        Cantidad.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        Cantidad.setText("Cantidad:");

        jLblPtId.setText("ProductoTamanioID");

        jLblPrecioCombo1.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLblPrecioCombo1.setText("Q.");

        jLblTamanio.setText("Tamanio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(627, 627, 627)
                .addComponent(jCmbTamanioProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTamanio)
                .addGap(589, 589, 589))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLblImgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNombreProducto)
                            .addComponent(jLblPtId)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblPrecioCombo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblPrecioCombo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JlblAdvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(653, 653, 653)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cantidad)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnMenos)
                                .addGap(6, 6, 6)
                                .addComponent(jTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jBtnMas))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLblDescpProducto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addComponent(JBtnRegresarProduc)
                        .addGap(74, 74, 74)
                        .addComponent(jBtnAñadirProduc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(655, 655, 655)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(536, 536, 536)
                        .addComponent(jLblWarningProducto)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLblImgProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblNombreProducto)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlblAdvertencia)
                            .addComponent(jLblPrecioCombo)
                            .addComponent(jLblPrecioCombo1))
                        .addGap(14, 14, 14)
                        .addComponent(jLblPtId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Cantidad)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnMenos)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnMas))))
                .addGap(45, 45, 45)
                .addComponent(jLblDescpProducto)
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbTamanioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTamanio))
                .addGap(12, 12, 12)
                .addComponent(jLblWarningProducto)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtnRegresarProduc)
                    .addComponent(jBtnAñadirProduc))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Cantidad;
    public javax.swing.JButton JBtnRegresarProduc;
    public javax.swing.JLabel JlblAdvertencia;
    public javax.swing.JButton jBtnAñadirProduc;
    public javax.swing.JButton jBtnMas;
    public javax.swing.JButton jBtnMenos;
    public javax.swing.JComboBox<String> jCmbTamanioProducto;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLblDescpProducto;
    public javax.swing.JLabel jLblImgProducto;
    public javax.swing.JLabel jLblNombreProducto;
    public javax.swing.JLabel jLblPrecioCombo;
    public javax.swing.JLabel jLblPrecioCombo1;
    public javax.swing.JLabel jLblPtId;
    public javax.swing.JLabel jLblTamanio;
    public javax.swing.JLabel jLblWarningProducto;
    public javax.swing.JTextField jTxtCantidad;
    // End of variables declaration//GEN-END:variables
}
