/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author javam2019
 */
public class jIntCIH1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form jIntComboIndividualHamburguesas
     */
    public jIntCIH1() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnIH1 = new javax.swing.JButton();
        jBtnCH1 = new javax.swing.JButton();
        jLblCH1 = new javax.swing.JLabel();
        jLblPrecioC1 = new javax.swing.JLabel();
        jLblIH1 = new javax.swing.JLabel();
        jLblPrecioI1 = new javax.swing.JLabel();

        jBtnIH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIH1ActionPerformed(evt);
            }
        });

        jBtnCH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCH1ActionPerformed(evt);
            }
        });

        jLblCH1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLblCH1.setText("Combo");

        jLblPrecioC1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLblPrecioC1.setText("Q50.00");

        jLblIH1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLblIH1.setText("Individual");

        jLblPrecioI1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLblPrecioI1.setText("Q20.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnCH1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnIH1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCH1)
                            .addComponent(jLblPrecioC1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLblPrecioI1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jLblIH1)))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jBtnCH1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblCH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblPrecioC1)
                .addGap(46, 46, 46)
                .addComponent(jBtnIH1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblIH1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblPrecioI1)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnIH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIH1ActionPerformed

    }//GEN-LAST:event_jBtnIH1ActionPerformed

    private void jBtnCH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCH1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnCH1;
    public javax.swing.JButton jBtnIH1;
    private javax.swing.JLabel jLblCH1;
    private javax.swing.JLabel jLblIH1;
    private javax.swing.JLabel jLblPrecioC1;
    private javax.swing.JLabel jLblPrecioI1;
    // End of variables declaration//GEN-END:variables
}
