/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author javam2019
 */
public class JintDescripcionCombo extends javax.swing.JInternalFrame {

    /**
     * Creates new form JintOrdernarH1
     */
    public JintDescripcionCombo() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNombreCombo = new javax.swing.JLabel();
        jLblImgCombo = new javax.swing.JLabel();
        jLblDescpCombo = new javax.swing.JLabel();
        jLblPrecioCombo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCmbTamanioCombo = new javax.swing.JComboBox<>();
        jLblSnackCombo = new javax.swing.JLabel();
        jCmbBebida = new javax.swing.JComboBox<>();
        JBtnRegresar = new javax.swing.JButton();
        jBtnAñadir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLblNombreCombo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLblNombreCombo.setText("Nombre Combo");

        jLblDescpCombo.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLblDescpCombo.setText("Descripción");

        jLblPrecioCombo.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        jLblPrecioCombo.setText("Precio");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel5.setText("Tamaño:");

        jCmbTamanioCombo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCmbTamanioCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLblSnackCombo.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLblSnackCombo.setText("Papas");

        jCmbBebida.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCmbBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JBtnRegresar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JBtnRegresar.setText("Regresar");

        jBtnAñadir.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBtnAñadir.setText("Añadir a la orden");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel7.setText("Bebida: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblDescpCombo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblImgCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblNombreCombo)
                                    .addComponent(jLblPrecioCombo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCmbTamanioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103)
                                        .addComponent(jLblSnackCombo))
                                    .addComponent(jLabel5))
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jCmbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBtnRegresar)
                        .addGap(75, 75, 75)
                        .addComponent(jBtnAñadir)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblNombreCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblPrecioCombo)
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addComponent(jLblImgCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblDescpCombo)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbTamanioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblSnackCombo)
                    .addComponent(jCmbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnRegresar)
                    .addComponent(jBtnAñadir))
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton JBtnRegresar;
    public javax.swing.JButton jBtnAñadir;
    public javax.swing.JComboBox<String> jCmbBebida;
    public javax.swing.JComboBox<String> jCmbTamanioCombo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLblDescpCombo;
    public javax.swing.JLabel jLblImgCombo;
    public javax.swing.JLabel jLblNombreCombo;
    public javax.swing.JLabel jLblPrecioCombo;
    public javax.swing.JLabel jLblSnackCombo;
    // End of variables declaration//GEN-END:variables
}
